- name: Render Docker Compose file 
  template:
    src: docker-compose.yml.j2
    dest: "{{ base_dir }}/docker-compose.yml"

- name: Copy ENV file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ app_dir }}/"
    mode: '0644'
  loop:
    - .env
- name: Copy Nginx files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ nginx_dir }}/"
    mode: '0644'
  loop:
    - nginx/default.conf
    - nginx/Dockerfile

- name: Copy php-fpm files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ fpm_dir }}/"
    mode: '0644'
  loop:
    - php-fpm/supervisord.conf
    - php-fpm/Dockerfile
    - php-fpm/uploads.ini

- name: Authenticate with Harbor Registry via Docker
  community.docker.docker_login:
      registry_url: "{{ harbor_registry }}"
      username: "{{ harbor_username }}"
      password: "{{ harbor_password }}"
  
- name: Check docker-compose containers
  command: docker compose ps -q
  args:
    chdir: "{{ base_dir }}"
  register: compose_status
  changed_when: false
  failed_when: false
    
- name: Stop and Clean Running Containers 
  command: docker compose down --remove-orphans 
  args:
    chdir: "{{ base_dir }}"
  when: compose_status.stdout | length > 0
    
- name: Pull latest images 
  command: docker compose pull 
  args:
    chdir: "{{ base_dir }}"
    
- name: Docker Containers Up
  command: docker compose up -d 
  args:
    chdir: "{{ base_dir }}"
