- name: Ensure Docker is installed 
  command: docker version 
  changed_when: false 

- name: Ensure Docker compose is installed 
  command: docker compose version 
  changed_when: false

# System Infrastructure 
- name: Create required Overlay network
  community.docker.docker_network:
    name: "{{ shared_network }}"
    driver: overlay
    attachable: true
    state: present
  run_once: true
  when: inventory_hostname == "stg-app-01"

- name: Label Swarm Cluster Nodes for Placement Constraints
  community.docker.docker_node:
    hostname: "{{ item.name }}"
    labels:
      id: "{{ item.label }}"
  loop:
    - { name: 'stg-app-01', label: 'node1' }
    - { name: 'stg-app-02', label: 'node2' }
  run_once: true
  delegate_to: stg-app-01

- name: Ensure Base directory exists 
  file:
    path: "{{ base_dir }}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Ensure nginx directory exists 
  file:
    path: "{{ nginx_dir }}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Ensure nginx logs directory exists 
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    mode: '0777'
    recurse: yes

- name: Ensure absolute Laravel storage folder skeleton exists with 777 permissions
  ansible.builtin.file:
    path: "{{ app_dir }}/{{ item }}"
    state: directory
    mode: '0777'
    recurse: yes
  loop:
    - storage
    - storage/logs
    - storage/framework
    - storage/framework/sessions
    - storage/framework/views
    - storage/framework/cache
    - storage/framework/cache/data
    - storage/app
    # - storage/app/public

# - name: Ensure database  directory exists 
#   file:
#     path: "{{ database_dir }}"
#     state: directory
#     mode: '0755'
#     recurse: yes

- name: Ensure php-fpm  directory exists 
  file:
    path: "{{ fpm_dir }}"
    state: directory
    mode: '0755'
    recurse: yes

- name: Ensure third-party-service-simul  directory exists 
  file:
    path: "{{ third_party_service_simul }}"
    state: directory
    mode: '0755'
    recurse: yes


