- name: Ensure Docker is installed 
  command: docker version 
  changed_when: false 

- name: Ensure Docker compose is installed 
  command: docker compose version 
  changed_when: false

- name: Ensure compose directory exists 
  file:
    path: "{{ compose_path }}"
    state: directory
    mode: '0755'
    recurse: yes
  
