application_networks: sena
appication_port: 9000
nginx_host_port: 8081
nginx_container_port: 80
db_port: 5432
base_dir: /opt/core-api
app_dir: /opt/core-api/core-api
nginx_dir: /opt/core-api/nginx
nginx_log_dir: /opt/core-api/nginx/logs
database_dir: /opt/core-api/db
fpm_dir: /opt/core-api/php-fpm
third-party-service-simul: /opt/core-api/third-party-service-simul